[main]
UPLOAD_FOLDER = "images"
VERIFICATIONS = "verifications"
SQLALCHEMY_ECHO = false
BADGE_IMAGE_DIR = "badge_images"
TASKCSV = "csv"

[encryption]
DEFAULT_ADMIN_PASSWORD = "password"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_EMAIL = "user@example.com"
SECRET_KEY = "changethiskey"
SESSION_COOKIE_SECURE = true
SESSION_COOKIE_NAME = "QuestsByCycles_Session"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_DOMAIN = false
SESSION_REFRESH_EACH_REQUEST = true
REMEMBER_COOKIE_DURATION_DAYS = 180

[flask]
SQLALCHEMY_DATABASE_URI = "postgresql://username:password@localhost/databasename7"
DEBUG = true
